# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.68.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "e610b2d7-660b-4cee-a47e-a44c3eb8a307"

default_platform :android

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  # build the release variant
  build_android_app(task: "assembleRelease")

  # upload to Beta by Crashlytics
  crashlytics(
    api_token: "50d9878dd763534eb2f4a720a90cad0668a04c9e",
    build_secret: "0285c26d11d1bb489ed32a46636ead3d9331fe5e61deb705a499b7f293245333"
  )
end
